[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14"

[build.cache]
  paths = ["node_modules/**/*", ".next/cache/**/*"]

  [[redirects]]
  from = "/"
  to "/page.tsx"
  status = 200